// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/nextmicro/logger"
	"github.com/nextmicro/next"
	"next.bff.layout/internal/biz"
	"next.bff.layout/internal/conf"
	"next.bff.layout/internal/data"
	"next.bff.layout/internal/server"
	"next.bff.layout/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init next application.
func wireApp(confData *conf.Data, client *conf.Client, loggerLogger logger.Logger) (*next.Next, func(), error) {
	shortUrlHTTPClient, err := data.NewGatewayClient(client)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, loggerLogger, shortUrlHTTPClient)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, loggerLogger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, loggerLogger)
	shortUrlRepo := data.NewShortUrlRepo(dataData, loggerLogger)
	shortUrlUsecase := biz.NewShortUrlUsecase(shortUrlRepo, loggerLogger)
	greeterService := service.NewGreeterService(greeterUsecase, shortUrlUsecase)
	grpcServer := server.NewGRPCServer(greeterService, loggerLogger)
	httpServer := server.NewHTTPServer(greeterService, loggerLogger)
	nextNext, err := newApp(loggerLogger, grpcServer, httpServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return nextNext, func() {
		cleanup()
	}, nil
}
